Rails.application.routes.draw do
  get 'revisao/detalhes' => 'revisao#detalhes'
  post 'revisao/detalhes' => 'revisao#detalhes'
  post 'pagamento/delete' => 'pagamento#delete'
  get 'revisao/delete' => 'revisao#delete'
  delete 'revisao/delete' => 'revisao#delete'
  post 'revisao/delete' => 'revisao#cadrev'
  post 'revisao/cadrev' => 'revisao#cadrev'
  post 'pagamento/consulta' => 'pagamento#delete'
  get 'carro/form' => 'carro#form'
  post 'carro/form' => 'carro#delete'
  delete 'carro/form' => 'carro#delete'
  get 'cliente/form' => 'cliente#form'
  post 'cliente/form' => 'cliente#update'
  delete 'cliente/updateform' => 'cliente#update'
  post 'cliente/updateform' => 'cliente#update'
  post 'cliente/consulta' => 'cliente#update'
  get 'reboque/cadreb' => 'reboque#listar'
  post 'reboque/cadreb' => 'reboque#cadreb'
  get 'revisao/cadrev' => 'revisao#listar'
  get 'pagamento/pagreg' => 'pagamento#registrar'
  get 'cliente/cadastro' => 'cliente#cadastrar'
  root 'index#index'
  get 'carro/cardastro' => 'carro#cardastrar'
  get 'carro/index' => 'root_path'
  get 'carro/consulta' => 'carro#consulta'
  post 'carro/cardastro' => 'carro#input'
  post 'cliente/cadastro' => 'cliente#clientnew'
  get 'cliente/consulta' => 'cliente#consulta'
  post 'pagamento/pagreg' => 'pagamento#cadastro'
  post 'pagamento/cadastro' => 'pagamento#cadastro'
  get 'pagamento/consulta' => 'pagamento#consulta'
  post 'carro/consulta' => 'carro#delete'
  get 'pagamento/form' => 'pagamento#renderform'
  get 'pagamento/delete' => 'pagamento#delete'
  post 'pagamento/form' => 'pagamento#delete'
  
  #post 'cliente/update' => 'cliente#update'
  resources :carro
  # <get / post / delete> `/nome da rota` => `controller#metodo`
end
